### ISSUE TITLE
关于在使用中得一些代码提示问题

### ISSUE THREAD

**Issue by JackTheMico** [toddlxt/Creator-TypeScript-Boilerplate#1]
首先，谢谢作者提供这么好的项目！WebStorm按照这个配置一下用起来比VS code舒服多了！依然有些小问题需要请教一下，如图：
![setinputcontrol](https://cloud.githubusercontent.com/assets/19216598/23393791/390536f8-fdc0-11e6-9b61-492c0884d350.png)
`cc.moveBy`**在webStorm中始终说参数不匹配，但我的参数应该是正确的：**
![paras](https://cloud.githubusercontent.com/assets/19216598/23393855/9e2263c6-fdc0-11e6-9ff0-5f3f8040e418.png)

**还有cc.EventListener.KEYBOARD点不出来：**
![keyboard](https://cloud.githubusercontent.com/assets/19216598/23393905/e0d3994c-fdc0-11e6-9161-8536704ef988.png)

**以及update(dt)方法也会报错：**
![udpateerr](https://cloud.githubusercontent.com/assets/19216598/23393971/57fb2d78-fdc1-11e6-855c-08694b424992.png)

代码其实就是官网上的“快速上手：制作第一个游戏”。现在转成typescript能在Creator上跑起来，但是webStrom中的这些报错还是感觉很恼火，请问作者有没有什么办法能解决这些问题？

**Comment by toddlxt** [comment]
@JackTheMico 很抱歉这么迟才看到你的问题。这些引擎函数的类型定义都在根目录的creator.d.ts中。creator.d.ts是Creator 1.3自带的，我根据自己使用TS的过程中发现的问题改了一些。
你这几个问题的修改方法如下：
1. cc.moveBy的函数签名在creator.d.ts的886行：
```
export function moveBy(duration: number, deltaPos: Vec2|number, deltaY: number): ActionInterval;
```
在deltaY后面加一个问号，变成可空参数即可：
```
export function moveBy(duration: number, deltaPos: Vec2|number, deltaY?: number): ActionInterval;
```
2. cc.EventListener的定义在creator.d.ts的6495行：
```
export class EventListener {
```
将它改为IEventListener并导出一个这个类的实例即可。即将6495行替换为这两行：
```
export let EventListener: IEventListener;
export class IEventListener {
```
3. cc.Component的update方法的定义在5304行：
```
update(): void;
```
给它添加一个可空的dt参数即可：
```
update(dt?: number): void;
```

**Comment by JackTheMico** [comment]
非常感谢！祝您身体健康，步步高升！
