### ISSUE TITLE
creator.d.ts文件没有更新，现在用1.4版的Cocos Creator开发，很多API提示有问题

### ISSUE THREAD

**Issue by lihuilai** [toddlxt/Creator-TypeScript-Boilerplate#2]
大大可以更新一下creator.d.ts文件或者列出使用TypeScript开发修改的代码提示部分吗

**Comment by toddlxt** [comment]
@lihuilai 感谢你的支持，官方的Creator 1.5测试版即将支持TypeScript了，我会把这些我自己在使用过程中发现API提示有问题的地方提供给官方，集成到新的Creator所带的creator.d.ts中。这个项目就不再维护了。
