### ISSUE TITLE
请问这个repo有新版本cocos creator可以跑起来的版本吗？

### ISSUE THREAD

**Issue by AthenaProgram** [toddlxt/Creator-TypeScript-Boilerplate#3]
您好！
最近入坑cocos creator，想学习ts，结果一个typescript的demo没有找到，然后您的这个项目尝试了一下也没run起来，请问有较新的版本吗？或者哪有其他ts的demo资源吗？
非常感谢！

**Comment by toddlxt** [comment]
Creator早已官方支持TS，下载一个最新版Creator，新建项目时选择Hello World Typescript版即可。
资源
http://forum.cocos.com/t/cocos-creator-typescript/56306
https://github.com/search?l=TypeScript&q=cocos+creator&type=Repositories&utf8=%E2%9C%93
